# Generated by Django 5.2.8 on 2025-12-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_category_thread_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='thread',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
