# Generated by Django 5.2.8 on 2026-01-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_category_options_thread_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='threads', to='forum.course'),
        ),
        migrations.AddField(
            model_name='thread',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='threads', to='forum.resource'),
        ),
    ]
