# Generated by Django 5.2.8 on 2026-01-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_resource_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(max_length=1000),
        ),
    ]
